#!/usr/bin/bash
# Fedora 25

ATOM_INSTALLED_VERSION=$(rpm -qi atom | grep "Version" |  cut -d ':' -f 2 | cut -d ' ' -f 2)
ATOM_LATEST_VERSION=$(curl -sL "https://api.github.com/repos/atom/atom/releases/latest" | grep -E "https.*atom-amd64.tar.gz" | cut -d '"' -f 4 | cut -d '/' -f 8 | sed 's/v//g')

if [[ $ATOM_INSTALLED_VERSION < $ATOM_LATEST_VERSION ]]; then
    echo "Atom is out of date!"
    echo "Installed version: $ATOM_INSTALLED_VERSION"
    echo "Available version: $ATOM_LATEST_VERSION"
fi
