#!/usr/bin/perl
my$pwd = $ENV{'PWD'};
my@repo = ('appmenu', 'backup', 'perl',
           'script', 'termise', 'timeline',
           'siteproject', 'siteproject/frontend', 'siteproject/backend', 
           'siteproject/db', 'siteproject/crawler',
           './vntyper/vntyper', './vntyper/vntyper-gtk',
           './uni/ktlt', 'keytrack', 'boxcrash'
        );

for (@repo) {
    if (-d $_) {
        print "Enter $_\n";
        chdir $_;
        system "git push";
        chdir $pwd;
        print "\n";
    }
}
