#!/bin/bash
if [ "$1" = "-u" ]
then
    scrot -zu $HOME/Pictures/screenshot/%Y-%m-%d-%H-%M-%S.png
else
    if [ "$1" = "-d" ]
    then
        scrot -z -d 3 $HOME/Pictures/screenshot/%Y-%m-%d-%H-%M-%S.png
    else
        scrot -z $HOME/Pictures/screenshot/%Y-%m-%d-%H-%M-%S.png
    fi
fi
