#!/usr/bin/bash
target=enp0s25
src=wlo1
ip='192.168.1.100/24'
ip link set up dev $target
ip addr add $ip dev $target
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o $src -j MASQUERADE
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $target -o $src -j ACCEPT
